## ทด

In [11]:
import pandas as pd
import numpy as np

rows = []

for f in curve_dir.glob("*.npy"):
    data = np.load(f, allow_pickle=True).item()
    rows.append(data)

Collection = pd.DataFrame(rows)
print(Collection[Collection.columns[0]])
print(Collection.head(1).confidences)
print(Collection.head(1).auc)



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado

AttributeError: _ARRAY_API not found

0      [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
1      [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
2      [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
3      [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
4      [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
                             ...                        
111    [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
112    [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
113    [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
114    [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
115    [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0...
Name: percentages, Length: 116, dtype: object
0    [0.16243742406368256, 0.09816581755876541, 0.8...
Name: confidences, dtype: object
0    0.924381
Name: auc, dtype: float64


In [12]:
print(str(Collection.iloc[1, 0]))
print(str(Collection.iloc[1, 1]))
print(str(Collection.iloc[1, 2]))



[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]
[0.8305776119232178, 0.9858338236808777, 0.8728751540184021, 0.9523787498474121, 0.9491590857505798, 0.9826993942260742, 0.9926400184631348, 0.9935170412063599, 0.9966241121292114, 0.9978463649749756, 0.9984676241874695, 0.9989197254180908, 0.9991222023963928, 0.9991282820701599, 0.9991328120231628, 0.9991379976272583, 0.9991419315338135, 0.9991426467895508, 0.9991169571876526, 0.9990904331207275, 0.9990271329879761]
0.9814388364553451


See Data in Saliency

In [13]:
import numpy as np

file_path = "/home/jovyan/work/MST/results/ODELIA/DinoV2ClassifierSlice_Final/attention_rollout/class_2/npy/08FEB48B_right_importance.npy"

data = np.load(file_path)

print("Type:", type(data))
print("Shape:", data.shape)
print("Dtype:", data.dtype)
print(data[1][1][0:14])
print("Data:", data)



Type: <class 'numpy.ndarray'>
Shape: (32, 224, 224)
Dtype: float32
[0.11320387 0.11320387 0.11320387 0.11320387 0.11320387 0.11320387
 0.11320387 0.11324187 0.11331788 0.11339393 0.11346994 0.11354595
 0.11362199 0.113698  ]
Data: [[[0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  ...
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]]

 [[0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  ...
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0

In [14]:
print(data)

[[[0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  ...
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]]

 [[0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  ...
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]
  [0.08766292 0.08766292 0.08766292 ... 0.1384719  0.1384719  0.1384719 ]]

 [[0.11320387 0.11320387 0.11320387 ... 0.09687314 0.09687314 0.09687314]
  [0.11320387 0.113203